### ISSUE TITLE
Using your embedded jQuery file

### ISSUE THREAD

**Issue by steinhaug** [comcaptain/chrome_plugins#2]
I couldnt access this in any way, wither with $, $jq or jQuery or $jQuery. Is it initiated in noconflict mode aswell and if so what is the name I should be using?

If it were up to me I would like to add the injection of jquery as the first js file and at the same time make it noconflict and rename it to $jQueryInjected or something other than the default jQuery names as some sites checks for theese to see if another lib installed.

Sure I could add it all myself inside the JS box. 

Also do I need to add code like this, assuming normal name for jquery:

`    $(document).ready(function() {
          // Code I want to run
    });`

I read in your update log you pointed out where things were injected so maby this is not needed for. I would love for just a few JS examples to look at, in case I am missing out on your embedded jquery file which has to be an ace trick instead of my current way - its kind of a boilerplate but works great:

```javascript
/*
 * Steinhaug v1.0 quick boilerplate for JS inject with Chrome extension plugin from 
 * //github.com/comcaptain/chrome_plugins
 */

/*
 * declare the variable name we want to use for jquery
 */
var $jQi = null;

/*
 * This is the the wrapper to run the code with injected jQuery as the name above
 */
function jQi_launch(){
    // $jQi() is your jQuery instance add contents here;

    // INSERT CODE HERE
}

/*
 * Function to load the external jquery into the page
 * NoConflict is also set as soon as possible and then we launch our 
 * wrapper above for the code.
 */
function dlJSAtOnload() {
    var jq = document.createElement('script');
    jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js";
    jq.onload = function(){ 
        $jQi = jQuery.noConflict(true);
        jQi_launch();
    }
    document.getElementsByTagName('head')[0].appendChild(jq);
}
/*
 * Event handlers so that adding the script does not happend before page has loaded
 */
if (window.addEventListener)
    window.addEventListener("load", dlJSAtOnload, false);
    else if (window.attachEvent)
    window.attachEvent("onload", dlJSAtOnload);
    else window.onload = dlJSAtOnload;
```

**Comment by comcaptain** [comment]
Just tried on this page, jQuery works fine and this is the js code I injected:
```javascript
$("document").ready(function() {
    alert("abc");
});
```
Can you tell me url of the page that you cannot use jQuery? Also your Chrome version

As to initializing jQuery in nonconflict mode, there is no need to do this. Because the injected js is executed in Chrome plugin's separate sandbox

**Comment by beasteers** [comment]
Is there a way to use the page's jQuery version? Because when I do `$(head).append('<script src="..."/>')` the jquery plugin gets added to the original jQuery version but I'm stuck with the injector's version so I can't access it
